import { ApiError } from "./client";
import { fixtureBoard, fixtureClassifiedFiles, fixtureConnections, fixtureCopyTypes, fixtureExports, fixtureParsedBrief, fixtureProjects, fixtureRules } from "./fixtures";
import type { AssistantAction, AssistantMessage, AssistantPlan, AssistantSession, BoardData, ClassifiedTypeFile, ConnectionStatus, CopyItem, CopyType, ExportRun, GenerationMode, GenerationRun, ParsedBrief, ParsedTypeBrief, Project, QcRule, ReviewPayload, RewriteSelectionPayload } from "./contracts";

const delay = (ms = 120) => new Promise((resolve) => window.setTimeout(resolve, ms));
const clone = <T,>(value: T): T => structuredClone(value);
let projects = clone(fixtureProjects);
let copyTypes = clone(fixtureCopyTypes);
let rules = clone(fixtureRules);
let board = clone(fixtureBoard);
let generationRuns: GenerationRun[] = [{ id: board.run_id, project_id: "p-demo", status: "completed", total_requested: board.items.length, batch_number: 1, label: "第 1 批", archived: false, created_at: new Date().toISOString() }];
const runItems = new Map<string, CopyItem[]>([[board.run_id, board.items]]);
const previewRemainders = new Map<string, CopyItem[]>();
let exportsHistory = clone(fixtureExports);
let classifiedFiles = clone(fixtureClassifiedFiles);
const assistantSessions = new Map<string, AssistantSession>();

export function resetMockApi() {
  projects = clone(fixtureProjects);
  copyTypes = clone(fixtureCopyTypes);
  rules = clone(fixtureRules);
  board = clone(fixtureBoard);
  generationRuns = [{ id: board.run_id, project_id: "p-demo", status: "completed", total_requested: board.items.length, batch_number: 1, label: "第 1 批", archived: false, created_at: new Date().toISOString() }];
  runItems.clear(); runItems.set(board.run_id, board.items);
  previewRemainders.clear();
  exportsHistory = clone(fixtureExports);
  classifiedFiles = clone(fixtureClassifiedFiles);
  assistantSessions.clear();
}

function emptyCopyType(projectId: string): CopyType {
  return { id: crypto.randomUUID(), project_id: projectId, name: "", quantity: 1, sources: ["manual"], input_modes: [], type_brief: "", requirements: { title_direction: "", body_structure: "", tone: "", persona: "", scenario: "", topic_requirements: "" }, must_include: [], must_avoid: [], references: [] };
}
function projectOrThrow(projectId: string) {
  const project = projects.find((item) => item.id === projectId);
  if (!project) throw new ApiError("PROJECT_NOT_FOUND", "项目不存在", 404);
  return project;
}
function canGenerateWith(type: CopyType) {
  return Boolean(type.type_brief.trim())
    || Boolean(type.input_modes.includes("reference_examples") && type.reference_profile?.confirmed)
    || Boolean(type.input_modes.includes("description_requirements") && Object.values(type.requirements).some((value) => value.trim()));
}

export const mockApi = {
  async listProjects(): Promise<Project[]> { await delay(); return clone(projects); },
  async getProject(projectId: string): Promise<Project> { await delay(); return clone(projectOrThrow(projectId)); },
  async createProject(input: Pick<Project, "name" | "brand" | "category">): Promise<Project> { const project: Project = { ...input, id: crypto.randomUUID(), status: "draft", updated_at: new Date().toISOString() }; projects = [project, ...projects]; await delay(); return clone(project); },
  async parseProjectBrief(projectId: string, input: { text?: string; file?: File }): Promise<ParsedBrief> { projectOrThrow(projectId); await delay(420); return clone({ ...fixtureParsedBrief, source_name: input.file?.name ?? "粘贴文本" }); },
  async saveProjectFindings(projectId: string, parsed: ParsedBrief): Promise<Project> { const project = projectOrThrow(projectId); project.status = "confirmed"; project.structured = { findings: parsed.findings }; project.updated_at = new Date().toISOString(); await delay(); return clone(project); },
  async listCopyTypes(projectId: string): Promise<CopyType[]> { await delay(); return clone(copyTypes.filter((item) => item.project_id === projectId)); },
  async createCopyType(projectId: string): Promise<CopyType> { const item = emptyCopyType(projectId); copyTypes = [...copyTypes, item]; await delay(); return clone(item); },
  async saveCopyType(item: CopyType): Promise<CopyType> { copyTypes = copyTypes.map((entry) => entry.id === item.id ? clone(item) : entry); await delay(); return clone(item); },
  async parseCopyTypeBrief(): Promise<ParsedTypeBrief> { await delay(350); return { requirements: { title_direction: "具体场景与轻微反差", body_structure: "场景 → 体验 → 产品事实 → 适用人群", tone: "自然克制", persona: "普通消费者", scenario: "从 Brief 原文识别的生活场景", topic_requirements: "品牌、产品与场景精准话题" }, sources: ["brief"], parsed_finding_count: 8, project_change_suggestions: [{ id: "type-brief-project-1", section: "brand", value: "微沫实验室", source_quote: "品牌：微沫实验室", confidence: 0.92, decision: "pending" }], conflicts: [{ id: "type-brief-conflict-1", section: "unclassified_requirement", value: "活动价待电商确认", source_quote: "活动：价格待确认", confidence: 0.68, decision: "pending" }] }; },
  async deleteCopyType(id: string): Promise<void> { copyTypes = copyTypes.filter((item) => item.id !== id); await delay(); },
  async analyzeReferences(): Promise<NonNullable<CopyType["reference_profile"]>> { await delay(500); return clone(fixtureCopyTypes[0].reference_profile!); },
  async listClassifiedFiles(projectId: string): Promise<ClassifiedTypeFile[]> { await delay(); return projectId === "p-demo" ? clone(classifiedFiles) : []; },
  async classifyTypeFiles(files: File[]): Promise<ClassifiedTypeFile[]> { await delay(420); const created = files.map((file) => ({ id: crypto.randomUUID(), filename: file.name, suggested_type: "待建立的新类型", evidence: "文件包含重复出现的场景与表达要求", confidence: "medium" as const })); classifiedFiles = [...classifiedFiles, ...created]; return clone(created); },
  async assignTypeFile(sourceId: string, copyTypeId: string | null): Promise<void> { classifiedFiles = classifiedFiles.map((file) => file.id === sourceId ? { ...file, assigned_type_id: copyTypeId } : file); await delay(); },
  async listRules(projectId: string): Promise<QcRule[]> { await delay(); return clone(rules.filter((rule) => rule.project_id === projectId)); },
  async saveRule(rule: QcRule): Promise<QcRule> { rules = rules.map((entry) => entry.id === rule.id ? clone(rule) : entry); await delay(); return clone(rule); },
  async createRule(projectId: string, rule: Omit<QcRule, "id" | "project_id">): Promise<QcRule> { const created = { ...rule, id: crypto.randomUUID(), project_id: projectId }; rules = [...rules, created]; await delay(); return clone(created); },
  async deleteRule(ruleId: string): Promise<void> { rules = rules.filter((item) => item.id !== ruleId); await delay(); },
  async getBoard(projectId: string, runId?: string): Promise<BoardData> { await delay(80); const visible = generationRuns.filter((run) => run.project_id === projectId && !run.archived); const selected = generationRuns.find((run) => run.id === runId && run.project_id === projectId) ?? visible[0]; return clone({ ...board, project_id: projectId, run_id: selected?.id ?? "", batch_number: selected?.batch_number, run_archived: selected?.archived ?? false, run_status: selected?.status === "running" ? "running" : selected ? "completed" : "idle", items: selected ? (runItems.get(selected.id) ?? []) : [] }); },
  async listGenerationRuns(projectId: string): Promise<GenerationRun[]> { await delay(); return clone(generationRuns.filter((run) => run.project_id === projectId).sort((a, b) => b.batch_number - a.batch_number)); },
  async createGenerationRun(projectId: string, generationMode: GenerationMode = "full"): Promise<GenerationRun> { const batchNumber = Math.max(0, ...generationRuns.filter((run) => run.project_id === projectId).map((run) => run.batch_number)) + 1; const projectTypes = copyTypes.filter((item) => item.project_id === projectId); const allItems = projectTypes.flatMap((type) => Array.from({ length: type.quantity }, (_, index): CopyItem => ({ id: `run-${Date.now()}-${type.id}-${index + 1}`, copy_type_id: type.id, copy_type_name: type.name || "未命名帖子类型", ordinal: index + 1, title: `${type.name || "新文案"} · 第 ${index + 1} 篇`, body: "这是模拟模型按当前 Brief、帖子类型和 QC 规则生成的文案。", tags: [type.name || "种草文案"], workflow_status: "completed", completion_reason: "ai_pass", version: 1, auto_rewrite_count: 0, findings: [], updated_at: new Date().toISOString() }))); const previewItemCount = generationMode === "preview" ? Math.min(3, allItems.length) : 0; const created: GenerationRun = { id: `run-${Date.now()}`, project_id: projectId, status: "completed", total_requested: allItems.length, batch_number: batchNumber, label: `第 ${batchNumber} 批`, archived: false, created_at: new Date().toISOString(), generation_mode: generationMode, generation_phase: generationMode === "preview" ? "awaiting_preview_approval" : "completed", preview_item_count: previewItemCount }; generationRuns = [created, ...generationRuns]; runItems.set(created.id, generationMode === "preview" ? allItems.slice(0, previewItemCount) : allItems); if (generationMode === "preview") previewRemainders.set(created.id, allItems.slice(previewItemCount)); await delay(240); return clone(created); },
  async confirmPreview(runId: string, expectedPreviewItemCount: number): Promise<GenerationRun> { const run = generationRuns.find((item) => item.id === runId)!; if (run.preview_item_count !== expectedPreviewItemCount) throw new ApiError("PREVIEW_ITEM_COUNT_MISMATCH", "预览数量已变化", 409); runItems.set(runId, [...(runItems.get(runId) ?? []), ...(previewRemainders.get(runId) ?? [])]); previewRemainders.delete(runId); run.generation_phase = "completed"; run.status = "completed"; await delay(180); return clone(run); },
  async getAssistantSession(projectId: string): Promise<AssistantSession> { const value = assistantSessions.get(projectId) ?? { id: `session-${projectId}`, project_id: projectId, messages: [] }; assistantSessions.set(projectId, value); await delay(); return clone(value); },
  async sendAssistantMessage(projectId: string, content: string): Promise<{ session_id: string; message: AssistantMessage; plan: AssistantPlan }> { const session = await this.getAssistantSession(projectId); const quantity = Number(content.match(/(\d+)\s*篇/)?.[1] ?? 0); const configuredTypes = copyTypes.filter((item) => item.project_id === projectId); const runnableTypes = configuredTypes.filter(canGenerateWith); const actions: AssistantAction[] = []; const blockers: string[] = []; if (quantity && runnableTypes.length === 1) actions.push({ client_action_id: crypto.randomUUID(), kind: "upsert_copy_type", payload: { id: runnableTypes[0].id, quantity } }); else if (quantity && configuredTypes.length === 0) actions.push({ client_action_id: crypto.randomUUID(), kind: "upsert_copy_type", payload: { name: "默认帖子类型", quantity, brief_text: content } }); else if (quantity && runnableTypes.length === 0) blockers.push("现有帖子类型还缺少类型 Brief、描述要求或已确认的参考案例。"); else if (quantity) blockers.push("当前有多个可用帖子类型，请说明这次要调整哪一个。"); else blockers.push("请告诉我希望生成多少篇文案。"); const plan: AssistantPlan = { summary: blockers.length ? "我已整理需求，还需要补齐帖子类型依据。" : "我已整理你的任务方向，会先用 3 篇预览确认文案感觉。", blockers, assumptions: ["未明确的产品事实会在生成前继续向你确认。"], actions }; const now = new Date().toISOString(); session.messages.push({ id: crypto.randomUUID(), role: "user", content, created_at: now }, { id: crypto.randomUUID(), role: "assistant", content: plan.summary, plan, created_at: now }); assistantSessions.set(projectId, session); await delay(220); return { session_id: session.id, message: clone(session.messages.at(-1)!), plan }; },
  async applyAssistantActions(projectId: string, actions: AssistantAction[]): Promise<{ results: Array<Record<string, unknown>> }> { for (const action of actions) { if (action.kind === "upsert_copy_type") { const quantity = Number(action.payload.quantity ?? 3); const existing = copyTypes.find((item) => item.project_id === projectId); if (existing) existing.quantity = quantity; else copyTypes = [...copyTypes, { ...emptyCopyType(projectId), name: String(action.payload.name ?? "默认帖子类型"), quantity, input_modes: ["description_requirements"] }]; } } const session = await this.getAssistantSession(projectId); session.messages.push({ id: crypto.randomUUID(), role: "system", content: "已更新任务配置。", created_at: new Date().toISOString() }); assistantSessions.set(projectId, session); await delay(); return { results: actions.map((action) => ({ kind: action.kind, applied: true })) }; },
  async setGenerationRunArchived(runId: string, archived: boolean): Promise<GenerationRun> { const run = generationRuns.find((item) => item.id === runId)!; run.archived = archived; run.archived_at = archived ? new Date().toISOString() : undefined; await delay(); return clone(run); },
  async retryQc(itemId: string): Promise<CopyItem> { const item = board.items.find((entry) => entry.id === itemId)!; item.workflow_status = "pending_ai_qc"; item.updated_at = new Date().toISOString(); await delay(); return clone(item); },
  async getItem(itemId: string): Promise<CopyItem> { const item = board.items.find((entry) => entry.id === itemId)!; await delay(40); return clone(item); },
  async saveItem(itemId: string, patch: Pick<CopyItem, "title" | "body" | "tags" | "version">): Promise<CopyItem> { const item = board.items.find((entry) => entry.id === itemId)!; Object.assign(item, patch, { version: item.version + 1, updated_at: new Date().toISOString() }); await delay(); return clone(item); },
  async rewriteSelection(itemId: string, payload: RewriteSelectionPayload): Promise<CopyItem> { const item = board.items.find((entry) => entry.id === itemId)!; if (item.version !== payload.expected_version) throw new ApiError("ITEM_VERSION_CONFLICT", "文案已产生新版本，请重新加载后再修改", 409); const source = item[payload.field]; const replacement = `${payload.selected_text}（已按“${payload.instruction}”调整）`; item[payload.field] = source.slice(0, payload.selection_start) + replacement + source.slice(payload.selection_end); item.version += 1; item.workflow_status = "human_review"; item.updated_at = new Date().toISOString(); await delay(450); return clone(item); },
  async reviewItem(itemId: string, payload: ReviewPayload): Promise<CopyItem> { const item = board.items.find((entry) => entry.id === itemId)!; if (payload.action === "force_pass") { if (!payload.legacy_issues?.length) throw new ApiError("FORCE_PASS_ISSUES_REQUIRED", "强制通过必须填写遗留问题", 400); if (payload.legacy_issues.some((issue) => !issue.trim())) throw new ApiError("REQUEST_VALIDATION_FAILED", "遗留问题不能包含空白项", 422); if (!payload.reason?.trim()) throw new ApiError("FORCE_PASS_REASON_REQUIRED", "强制通过必须填写放行理由", 400); } if (payload.action === "pass") { item.workflow_status = "completed"; item.completion_reason = "human_pass"; } if (payload.action === "force_pass") { item.workflow_status = "completed"; item.completion_reason = "forced_pass"; } if (payload.action === "reject") { item.workflow_status = "human_review"; item.review_disposition = "rejected"; } item.updated_at = new Date().toISOString(); await delay(); return clone(item); },
  async getConnections(): Promise<ConnectionStatus> { await delay(); return clone(fixtureConnections); },
  async listExports(projectId: string): Promise<ExportRun[]> { await delay(); return clone(exportsHistory.filter((item) => item.project_id === projectId)); },
  async createExport(projectId: string): Promise<ExportRun> { const selected = generationRuns.filter((run) => run.project_id === projectId && !run.archived).sort((a, b) => b.batch_number - a.batch_number)[0]; if (!selected) throw new ApiError("VISIBLE_GENERATION_RUN_REQUIRED", "当前没有可输出的显示中批次，请先恢复或新建一个批次", 400); const items = runItems.get(selected.id) ?? []; const created: ExportRun = { id: crypto.randomUUID(), project_id: projectId, generation_run_id: selected.id, status: "succeeded", sheet_id: `fake-${Date.now()}`, sheet_title: "8月种草·当前批次", row_count: items.filter((item) => item.workflow_status === "completed").length, adapter: "fake", created_at: new Date().toISOString() }; exportsHistory = [created, ...exportsHistory]; await delay(450); return clone(created); },
  async retryExport(exportId: string): Promise<ExportRun> { const run = exportsHistory.find((item) => item.id === exportId)!; run.status = "succeeded"; run.safe_error = undefined; await delay(350); return clone(run); },
  async getExportRun(exportId: string): Promise<ExportRun> { await delay(80); return clone(exportsHistory.find((item) => item.id === exportId)!); },
};
